
package com.gss.datavisualization.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StatisticPortService", targetNamespace = "http://originsystem.scut.com/webservice", wsdlLocation = "http://localhost:8001/ws/statistic.wsdl")
public class StatisticPortService
    extends Service
{

    private final static URL STATISTICPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException STATISTICPORTSERVICE_EXCEPTION;
    private final static QName STATISTICPORTSERVICE_QNAME = new QName("http://originsystem.scut.com/webservice", "StatisticPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8001/ws/statistic.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STATISTICPORTSERVICE_WSDL_LOCATION = url;
        STATISTICPORTSERVICE_EXCEPTION = e;
    }

    public StatisticPortService() {
        super(__getWsdlLocation(), STATISTICPORTSERVICE_QNAME);
    }

    public StatisticPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STATISTICPORTSERVICE_QNAME, features);
    }

    public StatisticPortService(URL wsdlLocation) {
        super(wsdlLocation, STATISTICPORTSERVICE_QNAME);
    }

    public StatisticPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STATISTICPORTSERVICE_QNAME, features);
    }

    public StatisticPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StatisticPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StatisticPort
     */
    @WebEndpoint(name = "StatisticPortSoap11")
    public StatisticPort getStatisticPortSoap11() {
        return super.getPort(new QName("http://originsystem.scut.com/webservice", "StatisticPortSoap11"), StatisticPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StatisticPort
     */
    @WebEndpoint(name = "StatisticPortSoap11")
    public StatisticPort getStatisticPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://originsystem.scut.com/webservice", "StatisticPortSoap11"), StatisticPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STATISTICPORTSERVICE_EXCEPTION!= null) {
            throw STATISTICPORTSERVICE_EXCEPTION;
        }
        return STATISTICPORTSERVICE_WSDL_LOCATION;
    }

}
