
package com.gss.datavisualization.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StatisticPort", targetNamespace = "http://originsystem.scut.com/webservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StatisticPort {


    /**
     * 
     * @param getGoodDetailListRequest
     * @return
     *     returns com.gss.datavisualization.webservice.GetGoodDetailListResponse
     */
    @WebMethod
    @WebResult(name = "getGoodDetailListResponse", targetNamespace = "http://originsystem.scut.com/webservice", partName = "getGoodDetailListResponse")
    public GetGoodDetailListResponse getGoodDetailList(
        @WebParam(name = "getGoodDetailListRequest", targetNamespace = "http://originsystem.scut.com/webservice", partName = "getGoodDetailListRequest")
        GetGoodDetailListRequest getGoodDetailListRequest);

    /**
     * 
     * @param getMerchantDetailListRequest
     * @return
     *     returns com.gss.datavisualization.webservice.GetMerchantDetailListResponse
     */
    @WebMethod
    @WebResult(name = "getMerchantDetailListResponse", targetNamespace = "http://originsystem.scut.com/webservice", partName = "getMerchantDetailListResponse")
    public GetMerchantDetailListResponse getMerchantDetailList(
        @WebParam(name = "getMerchantDetailListRequest", targetNamespace = "http://originsystem.scut.com/webservice", partName = "getMerchantDetailListRequest")
        GetMerchantDetailListRequest getMerchantDetailListRequest);

}
